---
kind: Service
apiVersion: v1
metadata:
  name: postgresql-cluster-nodeport
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 32345
      targetPort: 5432
      name: postgresql
  selector:
    application: spilo
    spilo-cluster: postgresql-cluster
    role: master
