k8s_masters:
  hosts:
    # Control nodes
    control1.home.local:
    # control2.home.local:
    # control3.home.local:
k8s_workers:
  hosts:
    # Worker nodes
    worker1.home.local:
    worker2.home.local:
    worker3.home.local:
k8s_cluster:
  children:
    k8s_masters:
      control1.home.local:
    k8s_workers:
      worker1.home.local:
      worker2.home.local:
      worker3.home.local: