k8s_masters:
  hosts:home
    # Control nodes
    control1.home.local:
    # control2.home.local:
    # control3.home.local:
k8s_workers:
  hosts:
    # Worker nodes
    worker1.home.local:
    worker2.home.local:
    worker3.home.local:
# k8s_cluster:
#   children:
#     k8s_masters:
#     k8s_workers:
